<a href="https://colab.research.google.com/github/LeonardoTostes90/ApostasEsportivas/blob/main/Base_Dados_Full.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#IMPORTANDO AS BIBLIOTECAS

In [9]:
import pandas as pd

#COLETANDO AS 5 ÚLTIMAS PLANILHAS DAS LIGAS PRINCIPAIS

In [10]:
# Inglaterra 1
ENG1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E0.csv")
ENG1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/E0.csv")
ENG1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/E0.csv")
ENG1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/E0.csv")
ENG1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/E0.csv")

ENG1 = [ENG1_01,ENG1_02,ENG1_03,ENG1_04,ENG1_05]
ENG1 = pd.concat(ENG1)
ENG1['Liga'] = 'Inglaterra 1'

# Inglaterra 2
ENG2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E1.csv")
ENG2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/E1.csv")
ENG2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/E1.csv")
ENG2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/E1.csv")
ENG2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/E1.csv")

ENG2 = [ENG2_01,ENG2_02,ENG2_03,ENG2_04,ENG2_05,]
ENG2 = pd.concat(ENG2)
ENG2['Liga'] = 'Inglaterra 2'

# Escócia 1
SCO1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SC0.csv")
SCO1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/SC0.csv")
SCO1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/SC0.csv")
SCO1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/SC0.csv")
SCO1_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/SC0.csv")

SCO1 = [SCO1_01,SCO1_02,SCO1_03,SCO1_05,SCO1_06]
SCO1 = pd.concat(SCO1)
SCO1['Liga'] = 'Escócia 1'

# Alemanha 1
GER1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/D1.csv")
GER1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/D1.csv")
GER1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/D1.csv")
GER1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/D1.csv")
GER1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/D1.csv")

GER1 = [GER1_01,GER1_02,GER1_03,GER1_04,GER1_05]
GER1 = pd.concat(GER1)
GER1['Liga'] = 'Alemanha 1'

# Alemanha 2
GER2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/D2.csv")
GER2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/D2.csv")
GER2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/D2.csv")
GER2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/D2.csv")
GER2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/D2.csv")

GER2 = [GER2_01,GER2_02,GER2_03,GER2_04,GER2_05]
GER2 = pd.concat(GER2)
GER2['Liga'] = 'Alemanha 2'

# Itália 1
ITA1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/I1.csv")
ITA1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/I1.csv")
ITA1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/I1.csv")
ITA1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/I1.csv")
ITA1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/I1.csv")

ITA1 = [ITA1_01,ITA1_02,ITA1_03,ITA1_04,ITA1_05]
ITA1 = pd.concat(ITA1)
ITA1['Liga'] = 'Itália 1'

# Itália 2
ITA2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/I2.csv")
ITA2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/I2.csv")
ITA2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/I2.csv")
ITA2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/I2.csv")
ITA2_06 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1617/I2.csv")

ITA2 = [ITA2_01,ITA2_02,ITA2_03,ITA2_05,ITA2_06]
ITA2 = pd.concat(ITA2)
ITA2['Liga'] = 'Itália 2'

# Espanha 1
SPA1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SP1.csv")
SPA1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/SP1.csv")
SPA1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/SP1.csv")
SPA1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/SP1.csv")
SPA1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/SP1.csv")

SPA1 = [SPA1_01,SPA1_02,SPA1_03,SPA1_04,SPA1_05]
SPA1 = pd.concat(SPA1)
SPA1['Liga'] = 'Espanha 1'

# Espanha 2
SPA2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SP2.csv")
SPA2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/SP2.csv")
SPA2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/SP2.csv")
SPA2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/SP2.csv")
SPA2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/SP2.csv")

SPA2 = [SPA2_01,SPA2_02,SPA2_03,SPA2_04,SPA2_05]
SPA2 = pd.concat(SPA2)
SPA2['Liga'] = 'Espanha 2'

# França 1
FRA1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/F1.csv")
FRA1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/F1.csv")
FRA1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/F1.csv")
FRA1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/F1.csv")
FRA1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/F1.csv")

FRA1 = [FRA1_01,FRA1_02,FRA1_03,FRA1_04,FRA1_05]
FRA1 = pd.concat(FRA1)
FRA1['Liga'] = 'França 1'

# França 2
FRA2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/F2.csv")
FRA2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/F2.csv")
FRA2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/F2.csv")
FRA2_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/F2.csv")
FRA2_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/F2.csv")

FRA2 = [FRA2_01,FRA2_02,FRA2_03,FRA2_04,FRA2_05]
FRA2 = pd.concat(FRA2)
FRA2['Liga'] = 'França 2'

# Holanda 1
NET1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/N1.csv")
NET1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/N1.csv")
NET1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/N1.csv")
NET1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/N1.csv")
NET1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/N1.csv")

NET1 = [NET1_01,NET1_02,NET1_03,NET1_04,NET1_05]
NET1 = pd.concat(NET1)
NET1['Liga'] = 'Holanda 1'

# Bélgica 1
BEL1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/B1.csv")
BEL1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/B1.csv")
BEL1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/B1.csv")
BEL1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/B1.csv")
BEL1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/B1.csv")

BEL1 = [BEL1_01,BEL1_02,BEL1_03,BEL1_04,BEL1_05]
BEL1 = pd.concat(BEL1)
BEL1['Liga'] = 'Bélgica 1'

# Portugal 1
POR1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/P1.csv")
POR1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/P1.csv")
POR1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/P1.csv")
POR1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/P1.csv")
POR1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/P1.csv")

POR1 = [POR1_01,POR1_02,POR1_03,POR1_04,POR1_05]
POR1 = pd.concat(POR1)
POR1['Liga'] = 'Portugal 1'

# Turquia 1
TUR1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/T1.csv")
TUR1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/T1.csv")
TUR1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/T1.csv")
TUR1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/T1.csv")
TUR1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/T1.csv")

TUR1 = [TUR1_01,TUR1_02,TUR1_03,TUR1_04,TUR1_05]
TUR1 = pd.concat(TUR1)
TUR1['Liga'] = 'Turquia 1'

# Grécia 1
GRE1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/G1.csv")
GRE1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/G1.csv")
GRE1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1920/G1.csv")
GRE1_04 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1819/G1.csv")
GRE1_05 = pd.read_csv("https://www.football-data.co.uk/mmz4281/1718/G1.csv")

GRE1 = [GRE1_01,GRE1_02,GRE1_03,GRE1_04,GRE1_05]
GRE1 = pd.concat(GRE1)
GRE1['Liga'] = 'Grécia 1'

#COLETANDO AS PLANILHAS DAS LIGAS SECUNDÁRIAS (TODAS AS TEMPORADAS EXISTENTES)

In [11]:
ARG = pd.read_csv("https://www.football-data.co.uk/new/ARG.csv")
ARG['Liga'] = 'Argentina'

AUS = pd.read_csv("https://www.football-data.co.uk/new/AUT.csv")
AUS['Liga'] = 'Austria'

BRA = pd.read_csv("https://www.football-data.co.uk/new/BRA.csv")
BRA['Liga'] = 'Brasil'

CHI = pd.read_csv("https://www.football-data.co.uk/new/CHN.csv")
CHI['Liga'] = 'China'

DIN = pd.read_csv("https://www.football-data.co.uk/new/DNK.csv")
DIN['Liga'] = 'Dinamarca'

FIN = pd.read_csv("https://www.football-data.co.uk/new/FIN.csv")
FIN['Liga'] = 'Finlândia'

IRL = pd.read_csv("https://www.football-data.co.uk/new/IRL.csv")
IRL['Liga'] = 'Irlanda'

JAP = pd.read_csv("https://www.football-data.co.uk/new/JPN.csv")
JAP['Liga'] = 'Japão'

MEX = pd.read_csv("https://www.football-data.co.uk/new/MEX.csv")
MEX['Liga'] = 'México'

NOR = pd.read_csv("https://www.football-data.co.uk/new/NOR.csv")
NOR['Liga'] = 'Noruega'

POL = pd.read_csv("https://www.football-data.co.uk/new/POL.csv")
POL['Liga'] = 'Polônia'

ROM = pd.read_csv("https://www.football-data.co.uk/new/ROU.csv")
ROM['Liga'] = 'Romêmia'

RUS = pd.read_csv("https://www.football-data.co.uk/new/RUS.csv")
RUS['Liga'] = 'Rússia'

SUE = pd.read_csv("https://www.football-data.co.uk/new/SWE.csv")
SUE['Liga'] = 'Suécia'

SUI = pd.read_csv("https://www.football-data.co.uk/new/SWZ.csv")
SUI['Liga'] = 'Suíça'

USA = pd.read_csv("https://www.football-data.co.uk/new/USA.csv")
USA['Liga'] = 'USA'

#CONCATENANDO AS PLANILHAS (PRINCIPAIS E SECUNDÁRIAS) EM DATAFRAMES DIFERENTES

In [12]:
df1 = [ENG1, ENG2, SCO1, GER1, GER2, ITA1, ITA2, SPA1, SPA2, FRA1, FRA2, NET1, BEL1, POR1, TUR1, GRE1]
df1 = pd.concat(df1)

df2 = [ARG, AUS, BRA, CHI, DIN, FIN, IRL, JAP, MEX, NOR, POL, ROM, RUS, SUE, SUI, USA]
df2 = pd.concat(df2)

#SELECIONANDO AS COLUNAS QUE SERÃO UTILIZADAS

In [13]:
df1 = df1[['Liga','Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR','B365H','B365D','B365A']]

df2 = df2[['Liga','Date','Home','Away','HG','AG','Res','PH','PD','PA']]

df1['Date'] = pd.to_datetime(df.Date)
df1['Date'] = pd.to_datetime(df.Date)

<ipython-input-13-517f6d4f8590>:5: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df1['Date'] = pd.to_datetime(df.Date)
<ipython-input-13-517f6d4f8590>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Date'] = pd.to_datetime(df.Date)
<ipython-input-13-517f6d4f8590>:6: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df1['Date'] = pd.to_datetime(df.Date)
<ipython-input-13-517f6d4f8590>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Date'] = pd.to_datetime(df.Date)

#RENOMEANDO AS COLUNAS E UNINDO OS DATAFRAMES

In [14]:
df1.columns = ['Liga','Data','Mandante','Visitante','Gols Mandante','Gols Visitante','Resultado','Odds Mandante','Odds Empate','Odds Visitante']

df2.columns = ['Liga','Data','Mandante','Visitante','Gols Mandante','Gols Visitante','Resultado','Odds Mandante','Odds Empate','Odds Visitante']

df = [df1, df2]
df = pd.concat(df)

#VISUALIZANDO O RESULTADO FINAL

In [15]:
df

,Liga,Data,Mandante,Visitante,Gols Mandante,Gols Visitante,Resultado,Odds Mandante,Odds Empate,Odds Visitante
0,Inglaterra 1,2022-05-08 00:00:00,Brentford,Arsenal,2.0,0.0,H,4.00,3.40,1.95
1,Inglaterra 1,2022-06-08 00:00:00,Man United,Leeds,5.0,1.0,H,1.53,4.50,5.75
2,Inglaterra 1,2022-06-08 00:00:00,Burnley,Brighton,1.0,2.0,A,3.10,3.10,2.45
3,Inglaterra 1,2022-06-08 00:00:00,Chelsea,Crystal Palace,3.0,0.0,H,1.25,5.75,13.00
4,Inglaterra 1,2022-06-08 00:00:00,Everton,Southampton,3.0,1.0,H,1.90,3.50,4.00
...,...,...,...,...,...,...,...,...,...,...
4564,USA,16/07/2023,Colorado Rapids,Houston Dynamo,0.0,0.0,D,2.49,3.31,3.09
4565,USA,16/07/2023,Real Salt Lake,New York Red Bulls,3.0,1.0,H,1.93,3.75,4.10
4566,USA,16/07/2023,Portland Timbers,Columbus Crew,3.0,2.0,H,2.12,3.91,3.34
4567,USA,16/07/2023,Seattle Sounders,FC Dallas,1.0,1.0,D,1.63,4.00,6.04
4568,USA,16/07/2023,Vancouver Whitecaps,Los Angeles Galaxy,4.0,2.0,H,1.93,4.34,3.58

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 76217 entries, 0 to 4568
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Liga            76217 non-null  object
 1   Data            74743 non-null  object
 2   Mandante        76217 non-null  object
 3   Visitante       76217 non-null  object
 4   Gols Mandante   76215 non-null  float64
 5   Gols Visitante  76215 non-null  float64
 6   Resultado       76215 non-null  object
 7   Odds Mandante   75960 non-null  float64
 8   Odds Empate     75960 non-null  float64
 9   Odds Visitante  75960 non-null  float64
dtypes: float64(5), object(5)
memory usage: 6.4+ MB

In [17]:
df = df.dropna()

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 74493 entries, 0 to 4568
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Liga            74493 non-null  object
 1   Data            74493 non-null  object
 2   Mandante        74493 non-null  object
 3   Visitante       74493 non-null  object
 4   Gols Mandante   74493 non-null  float64
 5   Gols Visitante  74493 non-null  float64
 6   Resultado       74493 non-null  object
 7   Odds Mandante   74493 non-null  float64
 8   Odds Empate     74493 non-null  float64
 9   Odds Visitante  74493 non-null  float64
dtypes: float64(5), object(5)
memory usage: 6.3+ MB

#EXPORTANDO O ARQUIVO FINAL PARA O EXCEL

In [19]:
df.to_excel("Base_de_Dados_Full.xlsx", index=False)